/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthResetpasswordImport } from './routes/auth/resetpassword'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppSettingsImport } from './routes/app/settings'
import { Route as AppHomeImport } from './routes/app/home'
import { Route as AppCampaignsIndexImport } from './routes/app/campaigns/index'
import { Route as AppCampaignsCampaignIdOverviewImport } from './routes/app/campaigns/$campaignId/overview'
import { Route as AppCampaignsCampaignIdMetricsImport } from './routes/app/campaigns/$campaignId/metrics'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetpasswordRoute = AuthResetpasswordImport.update({
  id: '/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppCampaignsIndexRoute = AppCampaignsIndexImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)

const AppCampaignsCampaignIdOverviewRoute =
  AppCampaignsCampaignIdOverviewImport.update({
    id: '/campaigns/$campaignId/overview',
    path: '/campaigns/$campaignId/overview',
    getParentRoute: () => AppRoute,
  } as any)

const AppCampaignsCampaignIdMetricsRoute =
  AppCampaignsCampaignIdMetricsImport.update({
    id: '/campaigns/$campaignId/metrics',
    path: '/campaigns/$campaignId/metrics',
    getParentRoute: () => AppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordImport
      parentRoute: typeof rootRoute
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsIndexImport
      parentRoute: typeof AppImport
    }
    '/app/campaigns/$campaignId/metrics': {
      id: '/app/campaigns/$campaignId/metrics'
      path: '/campaigns/$campaignId/metrics'
      fullPath: '/app/campaigns/$campaignId/metrics'
      preLoaderRoute: typeof AppCampaignsCampaignIdMetricsImport
      parentRoute: typeof AppImport
    }
    '/app/campaigns/$campaignId/overview': {
      id: '/app/campaigns/$campaignId/overview'
      path: '/campaigns/$campaignId/overview'
      fullPath: '/app/campaigns/$campaignId/overview'
      preLoaderRoute: typeof AppCampaignsCampaignIdOverviewImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppCampaignsCampaignIdMetricsRoute: typeof AppCampaignsCampaignIdMetricsRoute
  AppCampaignsCampaignIdOverviewRoute: typeof AppCampaignsCampaignIdOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppCampaignsCampaignIdMetricsRoute: AppCampaignsCampaignIdMetricsRoute,
  AppCampaignsCampaignIdOverviewRoute: AppCampaignsCampaignIdOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/app/campaigns/$campaignId/metrics': typeof AppCampaignsCampaignIdMetricsRoute
  '/app/campaigns/$campaignId/overview': typeof AppCampaignsCampaignIdOverviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/app/campaigns/$campaignId/metrics': typeof AppCampaignsCampaignIdMetricsRoute
  '/app/campaigns/$campaignId/overview': typeof AppCampaignsCampaignIdOverviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/app/campaigns/$campaignId/metrics': typeof AppCampaignsCampaignIdMetricsRoute
  '/app/campaigns/$campaignId/overview': typeof AppCampaignsCampaignIdOverviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/home'
    | '/app/settings'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/app/campaigns'
    | '/app/campaigns/$campaignId/metrics'
    | '/app/campaigns/$campaignId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/home'
    | '/app/settings'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/app/campaigns'
    | '/app/campaigns/$campaignId/metrics'
    | '/app/campaigns/$campaignId/overview'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/home'
    | '/app/settings'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/app/campaigns/'
    | '/app/campaigns/$campaignId/metrics'
    | '/app/campaigns/$campaignId/overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/auth/login",
        "/auth/resetpassword"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/home",
        "/app/settings",
        "/app/campaigns/",
        "/app/campaigns/$campaignId/metrics",
        "/app/campaigns/$campaignId/overview"
      ]
    },
    "/app/home": {
      "filePath": "app/home.tsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app/settings.tsx",
      "parent": "/app"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/resetpassword": {
      "filePath": "auth/resetpassword.tsx"
    },
    "/app/campaigns/": {
      "filePath": "app/campaigns/index.tsx",
      "parent": "/app"
    },
    "/app/campaigns/$campaignId/metrics": {
      "filePath": "app/campaigns/$campaignId/metrics.tsx",
      "parent": "/app"
    },
    "/app/campaigns/$campaignId/overview": {
      "filePath": "app/campaigns/$campaignId/overview.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
