/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthResetpasswordImport } from './routes/auth/resetpassword'
import { Route as AuthLogoutImport } from './routes/auth/logout'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppSettingsImport } from './routes/app/settings'
import { Route as AppHomeImport } from './routes/app/home'
import { Route as AppCampaignsImport } from './routes/app/campaigns'
import { Route as AppCampaignCampaignIdUsersImport } from './routes/app/campaign/$campaignId/users'
import { Route as AppCampaignCampaignIdTrafficImport } from './routes/app/campaign/$campaignId/traffic'
import { Route as AppCampaignCampaignIdRewardsImport } from './routes/app/campaign/$campaignId/rewards'
import { Route as AppCampaignCampaignIdOverviewImport } from './routes/app/campaign/$campaignId/overview'
import { Route as AppCampaignCampaignIdExportImport } from './routes/app/campaign/$campaignId/export'
import { Route as AppCampaignCampaignIdDemographicsImport } from './routes/app/campaign/$campaignId/demographics'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetpasswordRoute = AuthResetpasswordImport.update({
  id: '/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRoute,
} as any)

const AuthLogoutRoute = AuthLogoutImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppCampaignsRoute = AppCampaignsImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)

const AppCampaignCampaignIdUsersRoute = AppCampaignCampaignIdUsersImport.update(
  {
    id: '/campaign/$campaignId/users',
    path: '/campaign/$campaignId/users',
    getParentRoute: () => AppRoute,
  } as any,
)

const AppCampaignCampaignIdTrafficRoute =
  AppCampaignCampaignIdTrafficImport.update({
    id: '/campaign/$campaignId/traffic',
    path: '/campaign/$campaignId/traffic',
    getParentRoute: () => AppRoute,
  } as any)

const AppCampaignCampaignIdRewardsRoute =
  AppCampaignCampaignIdRewardsImport.update({
    id: '/campaign/$campaignId/rewards',
    path: '/campaign/$campaignId/rewards',
    getParentRoute: () => AppRoute,
  } as any)

const AppCampaignCampaignIdOverviewRoute =
  AppCampaignCampaignIdOverviewImport.update({
    id: '/campaign/$campaignId/overview',
    path: '/campaign/$campaignId/overview',
    getParentRoute: () => AppRoute,
  } as any)

const AppCampaignCampaignIdExportRoute =
  AppCampaignCampaignIdExportImport.update({
    id: '/campaign/$campaignId/export',
    path: '/campaign/$campaignId/export',
    getParentRoute: () => AppRoute,
  } as any)

const AppCampaignCampaignIdDemographicsRoute =
  AppCampaignCampaignIdDemographicsImport.update({
    id: '/campaign/$campaignId/demographics',
    path: '/campaign/$campaignId/demographics',
    getParentRoute: () => AppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsImport
      parentRoute: typeof AppImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutImport
      parentRoute: typeof rootRoute
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordImport
      parentRoute: typeof rootRoute
    }
    '/app/campaign/$campaignId/demographics': {
      id: '/app/campaign/$campaignId/demographics'
      path: '/campaign/$campaignId/demographics'
      fullPath: '/app/campaign/$campaignId/demographics'
      preLoaderRoute: typeof AppCampaignCampaignIdDemographicsImport
      parentRoute: typeof AppImport
    }
    '/app/campaign/$campaignId/export': {
      id: '/app/campaign/$campaignId/export'
      path: '/campaign/$campaignId/export'
      fullPath: '/app/campaign/$campaignId/export'
      preLoaderRoute: typeof AppCampaignCampaignIdExportImport
      parentRoute: typeof AppImport
    }
    '/app/campaign/$campaignId/overview': {
      id: '/app/campaign/$campaignId/overview'
      path: '/campaign/$campaignId/overview'
      fullPath: '/app/campaign/$campaignId/overview'
      preLoaderRoute: typeof AppCampaignCampaignIdOverviewImport
      parentRoute: typeof AppImport
    }
    '/app/campaign/$campaignId/rewards': {
      id: '/app/campaign/$campaignId/rewards'
      path: '/campaign/$campaignId/rewards'
      fullPath: '/app/campaign/$campaignId/rewards'
      preLoaderRoute: typeof AppCampaignCampaignIdRewardsImport
      parentRoute: typeof AppImport
    }
    '/app/campaign/$campaignId/traffic': {
      id: '/app/campaign/$campaignId/traffic'
      path: '/campaign/$campaignId/traffic'
      fullPath: '/app/campaign/$campaignId/traffic'
      preLoaderRoute: typeof AppCampaignCampaignIdTrafficImport
      parentRoute: typeof AppImport
    }
    '/app/campaign/$campaignId/users': {
      id: '/app/campaign/$campaignId/users'
      path: '/campaign/$campaignId/users'
      fullPath: '/app/campaign/$campaignId/users'
      preLoaderRoute: typeof AppCampaignCampaignIdUsersImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCampaignCampaignIdDemographicsRoute: typeof AppCampaignCampaignIdDemographicsRoute
  AppCampaignCampaignIdExportRoute: typeof AppCampaignCampaignIdExportRoute
  AppCampaignCampaignIdOverviewRoute: typeof AppCampaignCampaignIdOverviewRoute
  AppCampaignCampaignIdRewardsRoute: typeof AppCampaignCampaignIdRewardsRoute
  AppCampaignCampaignIdTrafficRoute: typeof AppCampaignCampaignIdTrafficRoute
  AppCampaignCampaignIdUsersRoute: typeof AppCampaignCampaignIdUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppHomeRoute: AppHomeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCampaignCampaignIdDemographicsRoute:
    AppCampaignCampaignIdDemographicsRoute,
  AppCampaignCampaignIdExportRoute: AppCampaignCampaignIdExportRoute,
  AppCampaignCampaignIdOverviewRoute: AppCampaignCampaignIdOverviewRoute,
  AppCampaignCampaignIdRewardsRoute: AppCampaignCampaignIdRewardsRoute,
  AppCampaignCampaignIdTrafficRoute: AppCampaignCampaignIdTrafficRoute,
  AppCampaignCampaignIdUsersRoute: AppCampaignCampaignIdUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/app/campaign/$campaignId/demographics': typeof AppCampaignCampaignIdDemographicsRoute
  '/app/campaign/$campaignId/export': typeof AppCampaignCampaignIdExportRoute
  '/app/campaign/$campaignId/overview': typeof AppCampaignCampaignIdOverviewRoute
  '/app/campaign/$campaignId/rewards': typeof AppCampaignCampaignIdRewardsRoute
  '/app/campaign/$campaignId/traffic': typeof AppCampaignCampaignIdTrafficRoute
  '/app/campaign/$campaignId/users': typeof AppCampaignCampaignIdUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/app/campaign/$campaignId/demographics': typeof AppCampaignCampaignIdDemographicsRoute
  '/app/campaign/$campaignId/export': typeof AppCampaignCampaignIdExportRoute
  '/app/campaign/$campaignId/overview': typeof AppCampaignCampaignIdOverviewRoute
  '/app/campaign/$campaignId/rewards': typeof AppCampaignCampaignIdRewardsRoute
  '/app/campaign/$campaignId/traffic': typeof AppCampaignCampaignIdTrafficRoute
  '/app/campaign/$campaignId/users': typeof AppCampaignCampaignIdUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/home': typeof AppHomeRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/app/campaign/$campaignId/demographics': typeof AppCampaignCampaignIdDemographicsRoute
  '/app/campaign/$campaignId/export': typeof AppCampaignCampaignIdExportRoute
  '/app/campaign/$campaignId/overview': typeof AppCampaignCampaignIdOverviewRoute
  '/app/campaign/$campaignId/rewards': typeof AppCampaignCampaignIdRewardsRoute
  '/app/campaign/$campaignId/traffic': typeof AppCampaignCampaignIdTrafficRoute
  '/app/campaign/$campaignId/users': typeof AppCampaignCampaignIdUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/campaigns'
    | '/app/home'
    | '/app/settings'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/resetpassword'
    | '/app/campaign/$campaignId/demographics'
    | '/app/campaign/$campaignId/export'
    | '/app/campaign/$campaignId/overview'
    | '/app/campaign/$campaignId/rewards'
    | '/app/campaign/$campaignId/traffic'
    | '/app/campaign/$campaignId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/campaigns'
    | '/app/home'
    | '/app/settings'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/resetpassword'
    | '/app/campaign/$campaignId/demographics'
    | '/app/campaign/$campaignId/export'
    | '/app/campaign/$campaignId/overview'
    | '/app/campaign/$campaignId/rewards'
    | '/app/campaign/$campaignId/traffic'
    | '/app/campaign/$campaignId/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/campaigns'
    | '/app/home'
    | '/app/settings'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/resetpassword'
    | '/app/campaign/$campaignId/demographics'
    | '/app/campaign/$campaignId/export'
    | '/app/campaign/$campaignId/overview'
    | '/app/campaign/$campaignId/rewards'
    | '/app/campaign/$campaignId/traffic'
    | '/app/campaign/$campaignId/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/auth/login",
        "/auth/logout",
        "/auth/resetpassword"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/campaigns",
        "/app/home",
        "/app/settings",
        "/app/campaign/$campaignId/demographics",
        "/app/campaign/$campaignId/export",
        "/app/campaign/$campaignId/overview",
        "/app/campaign/$campaignId/rewards",
        "/app/campaign/$campaignId/traffic",
        "/app/campaign/$campaignId/users"
      ]
    },
    "/app/campaigns": {
      "filePath": "app/campaigns.tsx",
      "parent": "/app"
    },
    "/app/home": {
      "filePath": "app/home.tsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app/settings.tsx",
      "parent": "/app"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/logout": {
      "filePath": "auth/logout.tsx"
    },
    "/auth/resetpassword": {
      "filePath": "auth/resetpassword.tsx"
    },
    "/app/campaign/$campaignId/demographics": {
      "filePath": "app/campaign/$campaignId/demographics.tsx",
      "parent": "/app"
    },
    "/app/campaign/$campaignId/export": {
      "filePath": "app/campaign/$campaignId/export.tsx",
      "parent": "/app"
    },
    "/app/campaign/$campaignId/overview": {
      "filePath": "app/campaign/$campaignId/overview.tsx",
      "parent": "/app"
    },
    "/app/campaign/$campaignId/rewards": {
      "filePath": "app/campaign/$campaignId/rewards.tsx",
      "parent": "/app"
    },
    "/app/campaign/$campaignId/traffic": {
      "filePath": "app/campaign/$campaignId/traffic.tsx",
      "parent": "/app"
    },
    "/app/campaign/$campaignId/users": {
      "filePath": "app/campaign/$campaignId/users.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
